/**
 * CoverageReport Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: coverage-reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/coverage-reports.openapi.types.js";
import { schemas } from "../schemas/coverage-reports.schemas.js";

/**
 * Entity: CoverageReportEntity
 * Description: Represents the CoverageReport domain model.
 * Source: schemas.CoverageReport
 * Type: Domain Entity (API)
 */
export const CoverageReportEntitySchema = schemas.CoverageReport;
export type CoverageReportEntity = components["schemas"]["CoverageReport"];
