/**
 * CoverageReportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: coverage-reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CoverageReportRepository Port
 *
 * DDD: Application port for coveragereportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCoverageReportInput, CreateCoverageReportOutput, GetCoverageReportInput, GetCoverageReportOutput, ListCoverageReportsInput, ListCoverageReportsOutput } from "../dto/coverage-report.dto";
export interface CoverageReportRepository {
  listCoverageReports(input: ListCoverageReportsInput): Promise<ListCoverageReportsOutput>;
  createCoverageReport(input: CreateCoverageReportInput): Promise<CreateCoverageReportOutput>;
  getCoverageReport(input: GetCoverageReportInput): Promise<GetCoverageReportOutput>;
}

export type { CreateCoverageReportInput, CreateCoverageReportOutput, GetCoverageReportInput, GetCoverageReportOutput, ListCoverageReportsInput, ListCoverageReportsOutput } from "../dto/coverage-report.dto";
