/**
 * Integration DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: integrations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Integration DTOs
 *
 * DDD: Application DTOs for Integration use cases.
 */

import type { GetIntegrationParams, ListIntegrationsParams, RegisterIntegrationRequestInput } from "@selfsignal/core/integrations/types";

export type ListIntegrationsInput = ListIntegrationsParams;

export type RegisterIntegrationInput = RegisterIntegrationRequestInput;

export type GetIntegrationInput = GetIntegrationParams;

export type ListIntegrationsOutput = {};

export type RegisterIntegrationOutput = {};

export type GetIntegrationOutput = {};
