/**
 * ExecuteGetCampaign - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCampaign Use Case
 *
 * DDD: Application use case for get Campaign.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCampaignInput, GetCampaignOutput } from "../dto/campaign.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { CampaignRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetCampaign {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly campaign: CampaignRepository
  ) {}

  async execute(input: GetCampaignInput): Promise<GetCampaignOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmpId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).campaignId) {
      throw new ValidationError("campaignId is required");
    }
    const campaignId = (input as any).campaignId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.campaign.getCampaign({ campaignId: campaignId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${campaignId}`);
    }

    return entity as GetCampaignOutput;
  }
}
