/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the vault-profiles domain.
 * Use these factories in tests to create test data.
 */

export { createCreateEraseRequest } from "./erase/dto/create-erase.dto.factory.js";
export { createVaultProfile } from "./vault-profile/entity/vault-profile.entity.factory.js";
