/**
 * Routes for VaultProfile
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createVaultProfile, getVaultProfile, listVaultProfiles, updateVaultProfile } from "../handlers/vault-profile.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function vaultProfileRoutes(fastify: FastifyInstance) {
  // POST /v1/vault-profiles (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/vault-profiles",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVaultProfilesDependenciesForRequest();
        await createVaultProfile(request, reply, deps);
      });
    }
  );


  // GET /v1/vault-profiles (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/vault-profiles",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVaultProfilesDependenciesForRequest();
        await listVaultProfiles(request, reply, deps);
      });
    }
  );


  // GET /v1/vault-profiles/{personId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/vault-profiles/:personId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { personId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVaultProfilesDependenciesForRequest();
        await getVaultProfile(request, reply, deps);
      });
    }
  );


  // PATCH /v1/vault-profiles/{personId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/vault-profiles/:personId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { personId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVaultProfilesDependenciesForRequest();
        await updateVaultProfile(request, reply, deps);
      });
    }
  );


}
