/**
 * Handlers for Replay
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signal-activations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SignalActivationsDomainModule } from "../dependencies/signal-activations-ddd.dependencies.js";
import type { ReplaySignalActivationInput } from "@selfsignal/services/signal-activations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/signal-activations/{activationId}/replay
 * Operation: replaySignalActivation
 */
export async function replaySignalActivation(
  request: FastifyRequest<{ Params: { activationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SignalActivationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ReplaySignalActivationInput = {
    activationId: request.params.activationId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.replays.get.execute(input);
  return reply.code(200).send(result);
}


