/**
 * CloseComplaintCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaint-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { closeComplaintCase } from "/api-server/domains/complaint-cases/handlers";
import type { ComplaintCasesDDDDependencies } from "/api-server/domains/complaint-cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { COMPLAINTCASES_USE_CASES } from "../__factories__/use-cases.js";

describe("CloseComplaintCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ComplaintCasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ComplaintCasesDDDDependencies>(
      COMPLAINTCASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCloseComplaintCase, "execute").mockResolvedValue(useCaseResult);

    await closeComplaintCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCloseComplaintCase.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
