/**
 * Handlers for Attestation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AuditExportsDomainModule } from "../dependencies/audit-exports-ddd.dependencies.js";
import type { GetPublicAttestationInput } from "@selfsignal/services/audit-exports";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/public/attestations/{exportId}
 * Operation: getPublicAttestation
 */
export async function getPublicAttestation(
  request: FastifyRequest<{ Params: { exportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AuditExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPublicAttestationInput = {
    exportId: request.params.exportId,
  };
  const result = await deps.useCases.attestations.get.execute(input);
  return reply.code(200).send(result);
}


