/**
 * Handlers for AuditExport
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AuditExportsDomainModule } from "../dependencies/audit-exports-ddd.dependencies.js";
import type { CreateAuditExportInput, GetAuditExportInput, ListAuditExportsInput } from "@selfsignal/services/audit-exports";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/audit-exports
 * Operation: listAuditExports
 */
export async function listAuditExports(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AuditExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAuditExportsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.auditExports.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/audit-exports
 * Operation: createAuditExport
 */
export async function createAuditExport(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AuditExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAuditExportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.auditExports.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/audit-exports/{exportId}
 * Operation: getAuditExport
 */
export async function getAuditExport(
  request: FastifyRequest<{ Params: { exportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AuditExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAuditExportInput = {
    exportId: request.params.exportId,
  };
  const result = await deps.useCases.auditExports.get.execute(input);
  return reply.code(200).send(result);
}


