/**
 * GetIntegration handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: integrations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getIntegration } from "/api-server/domains/integrations/handlers";
import type { IntegrationsDDDDependencies } from "/api-server/domains/integrations";
import { createIntegration as createIntegrationEntity } from "/factories/integrations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { INTEGRATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetIntegration", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IntegrationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IntegrationsDDDDependencies>(
      INTEGRATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createIntegrationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetIntegration, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { integrationId: entity.id };

    await getIntegration(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetIntegration.execute).toHaveBeenCalledWith(expect.objectContaining({ integrationId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { integrationId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetIntegration, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getIntegration(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
