/**
 * RegisterIntegration handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: integrations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { registerIntegration } from "/api-server/domains/integrations/handlers";
import type { IntegrationsDDDDependencies } from "/api-server/domains/integrations";
import { createIntegration as createIntegrationEntity } from "/factories/integrations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { INTEGRATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("RegisterIntegration", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: IntegrationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<IntegrationsDDDDependencies>(
      INTEGRATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createIntegrationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRegisterIntegration, "execute").mockResolvedValue(useCaseResult);

    await registerIntegration(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRegisterIntegration.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
