/**
 * ConsentGrant Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent-grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ConsentGrantEntity } from "@selfsignal/core/consent-grants/models/index.js";
import { consentGrantsSchemas } from "@selfsignal/core/consent-grants";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cgr";

export function createConsentGrant(overrides: Partial<ConsentGrantEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cgr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    controllerIntegrationId: overrides.controllerIntegrationId ?? faker.string.uuid(),
    expiresAt: overrides.expiresAt ?? new Date().toISOString(),
    personId: overrides.personId ?? faker.string.uuid(),
    purposeId: overrides.purposeId ?? faker.string.uuid(),
    signalClasses: overrides.signalClasses ?? [],
    status: overrides.status ?? "active",
    ...overrides,
  };

  return consentGrantsSchemas.ConsentGrant.parse(raw);
}

export function consentGrantBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createConsentGrant(overrides));
}
