/**
 * Routes for SignalActivation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signal-activations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSignalActivation, listSignalActivations, requestSignalActivation } from "../handlers/signal-activation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function signalActivationRoutes(fastify: FastifyInstance) {
  // GET /v1/signal-activations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/signal-activations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSignalActivationsDependenciesForRequest();
        await listSignalActivations(request, reply, deps);
      });
    }
  );


  // POST /v1/signal-activations (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/signal-activations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSignalActivationsDependenciesForRequest();
        await requestSignalActivation(request, reply, deps);
      });
    }
  );


  // GET /v1/signal-activations/{activationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/signal-activations/:activationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { activationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSignalActivationsDependenciesForRequest();
        await getSignalActivation(request, reply, deps);
      });
    }
  );


}
