/**
 * ExecuteFulfilRightsRequest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-requests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteFulfilRightsRequest Use Case
 *
 * DDD: Application use case for get Fulfil.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { FulfilRightsRequestInput, FulfilRightsRequestOutput } from "../dto/fulfil.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { FulfilRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteFulfilRightsRequest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fulfil: FulfilRepository
  ) {}

  async execute(input: FulfilRightsRequestInput): Promise<FulfilRightsRequestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rrqId();

    // All field names extracted from OpenAPI spec: evidencePackHash, notes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).requestId) {
      throw new ValidationError("requestId is required");
    }
    const requestId = (input as any).requestId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.fulfil.fulfilRightsRequest({ requestId: requestId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${requestId}`);
    }

    return entity as FulfilRightsRequestOutput;
  }
}
