/**
 * ExecuteCreateRightsRequest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-requests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateRightsRequest Use Case
 *
 * DDD: Application use case for create RightsRequest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateRightsRequestInput, CreateRightsRequestOutput } from "../dto/rights-request.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { RightsRequestRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateRightsRequest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rightsRequest: RightsRequestRepository
  ) {}

  async execute(input: CreateRightsRequestInput): Promise<CreateRightsRequestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rrqId();

    // All field names extracted from OpenAPI spec: notes, personId, rightType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.personId) {
      throw new ValidationError("personId is required");
    }
    if (!input.rightType) {
      throw new ValidationError("rightType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (rights-requests domain)
    const entityId = this.idGenerator.rrqId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.rightsRequest.createRightsRequest({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateRightsRequestOutput;
  }
}
