/**
 * WithdrawRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent-grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WithdrawRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements WithdrawRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  WithdrawRepository,
} from "@selfsignal/services/consent-grants";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { WithdrawRepositoryDdb } from "./withdraw-repository.ddb.js";

/**
 * WithdrawRepositoryAdapter
 *
 * Implements WithdrawRepository port for infrastructure layer.
 */
export class WithdrawRepositoryAdapter implements WithdrawRepository {
  private readonly ddb: WithdrawRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new WithdrawRepositoryDdb(this.dynamoClient);
  }

  async withdrawConsentGrant(input: Parameters<WithdrawRepository['withdrawConsentGrant']>[0]): Promise<Awaited<ReturnType<WithdrawRepository['withdrawConsentGrant']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.withdrawConsentGrant(input);
  }
}
