/**
 * FulfilRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-requests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FulfilRepository Port
 *
 * DDD: Application port for fulfilrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { FulfilRightsRequestInput, FulfilRightsRequestOutput } from "../dto/fulfil.dto";
export interface FulfilRepository {
  fulfilRightsRequest(input: FulfilRightsRequestInput): Promise<FulfilRightsRequestOutput>;
}

export type { FulfilRightsRequestInput, FulfilRightsRequestOutput } from "../dto/fulfil.dto";
