/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@selfsignal/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "audit-exports", "campaigns", "complaint-cases", "consent-grants", "coverage-reports", "identity", "integrations", "purposes", "rights-requests", "signal-activations", "vault-profiles"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      "audit-exports": [{ method: "GET", path: "/v1/audit-exports" }, { method: "POST", path: "/v1/audit-exports" }, { method: "GET", path: "/v1/audit-exports/:exportId" }, { method: "POST", path: "/v1/audit-exports/:exportId/verify" }, { method: "GET", path: "/v1/public/attestations/:exportId" }],
      campaigns: [{ method: "GET", path: "/v1/campaigns" }, { method: "POST", path: "/v1/campaigns" }, { method: "GET", path: "/v1/campaigns/:campaignId" }, { method: "POST", path: "/v1/campaigns/:campaignId/compliance-gate" }],
      "complaint-cases": [{ method: "GET", path: "/v1/complaint-cases" }, { method: "POST", path: "/v1/complaint-cases" }, { method: "GET", path: "/v1/complaint-cases/:complaintId" }, { method: "POST", path: "/v1/complaint-cases/:complaintId/escalate" }, { method: "POST", path: "/v1/complaint-cases/:complaintId/close" }],
      "consent-grants": [{ method: "GET", path: "/v1/consent-grants" }, { method: "POST", path: "/v1/consent-grants" }, { method: "GET", path: "/v1/consent-grants/:grantId" }, { method: "POST", path: "/v1/consent-grants/:grantId/withdraw" }, { method: "POST", path: "/v1/consent-grants/:grantId/renew" }],
      "coverage-reports": [{ method: "GET", path: "/v1/coverage-reports" }, { method: "POST", path: "/v1/coverage-reports" }, { method: "GET", path: "/v1/coverage-reports/:reportId" }, { method: "GET", path: "/v1/coverage-reports/latest" }],
      identity: [],
      integrations: [{ method: "GET", path: "/v1/integrations" }, { method: "POST", path: "/v1/integrations" }, { method: "GET", path: "/v1/integrations/:integrationId" }],
      purposes: [{ method: "GET", path: "/v1/purposes" }, { method: "POST", path: "/v1/purposes" }, { method: "GET", path: "/v1/purposes/:purposeId" }, { method: "PATCH", path: "/v1/purposes/:purposeId" }],
      "rights-requests": [{ method: "GET", path: "/v1/rights-requests" }, { method: "POST", path: "/v1/rights-requests" }, { method: "GET", path: "/v1/rights-requests/:requestId" }, { method: "POST", path: "/v1/rights-requests/:requestId/fulfil" }],
      "signal-activations": [{ method: "GET", path: "/v1/signal-activations" }, { method: "POST", path: "/v1/signal-activations" }, { method: "GET", path: "/v1/signal-activations/:activationId" }, { method: "POST", path: "/v1/signal-activations/:activationId/replay" }],
      "vault-profiles": [{ method: "GET", path: "/v1/vault-profiles" }, { method: "POST", path: "/v1/vault-profiles" }, { method: "GET", path: "/v1/vault-profiles/:personId" }, { method: "PATCH", path: "/v1/vault-profiles/:personId" }, { method: "POST", path: "/v1/vault-profiles/:personId/erase" }, { method: "GET", path: "/v1/vault-profiles/:personId/data-pack" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
