/**
 * ExecuteListComplaintCases - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaint-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListComplaintCases Use Case
 *
 * DDD: Application use case for list ComplaintCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListComplaintCasesInput, ListComplaintCasesOutput } from "../dto/complaint-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { ComplaintCaseRepository } from "../ports";

export class ExecuteListComplaintCases {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complaintCase: ComplaintCaseRepository
  ) {}

  async execute(input: ListComplaintCasesInput): Promise<ListComplaintCasesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cpcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.complaintCase.listComplaintCases({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListComplaintCasesOutput;
  }
}
