/**
 * ExecuteEscalateComplaintCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaint-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteEscalateComplaintCase Use Case
 *
 * DDD: Application use case for get Escalate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { EscalateComplaintCaseInput, EscalateComplaintCaseOutput } from "../dto/escalate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { EscalateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteEscalateComplaintCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly escalate: EscalateRepository
  ) {}

  async execute(input: EscalateComplaintCaseInput): Promise<EscalateComplaintCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cpcId();

    // All field names extracted from OpenAPI spec: authorityRef, notes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).complaintId) {
      throw new ValidationError("complaintId is required");
    }
    const complaintId = (input as any).complaintId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.escalate.escalateComplaintCase({ complaintId: complaintId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${complaintId}`);
    }

    return entity as EscalateComplaintCaseOutput;
  }
}
