/**
 * Integration Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: integrations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/integrations.openapi.types.js";
import { schemas } from "../schemas/integrations.schemas.js";

/**
 * Entity: IntegrationEntity
 * Description: Represents the Integration domain model.
 * Source: schemas.Integration
 * Type: Domain Entity (API)
 */
export const IntegrationEntitySchema = schemas.Integration;
export type IntegrationEntity = components["schemas"]["Integration"];
