/**
 * Handlers for VaultProfile
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { VaultProfilesDomainModule } from "../dependencies/vault-profiles-ddd.dependencies.js";
import type { CreateVaultProfileInput, GetVaultProfileInput, ListVaultProfilesInput, UpdateVaultProfileInput } from "@selfsignal/services/vault-profiles";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/vault-profiles
 * Operation: listVaultProfiles
 */
export async function listVaultProfiles(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: VaultProfilesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListVaultProfilesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.vaultProfiles.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/vault-profiles
 * Operation: createVaultProfile
 */
export async function createVaultProfile(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: VaultProfilesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateVaultProfileInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.vaultProfiles.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/vault-profiles/{personId}
 * Operation: getVaultProfile
 */
export async function getVaultProfile(
  request: FastifyRequest<{ Params: { personId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VaultProfilesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetVaultProfileInput = {
    personId: request.params.personId,
  };
  const result = await deps.useCases.vaultProfiles.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/vault-profiles/{personId}
 * Operation: updateVaultProfile
 */
export async function updateVaultProfile(
  request: FastifyRequest<{ Params: { personId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VaultProfilesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateVaultProfileInput = {
    personId: request.params.personId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.vaultProfiles.update.execute(input);
  return reply.code(200).send(result);
}


