/**
 * CoverageReports DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: coverage-reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CoverageReports Domain Module - Composition root
 *
 * DDD: Composition root for coverage-reports domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CoverageReportRepositoryAdapter,
  LatestRepositoryAdapter,
} from "@selfsignal/adapters/coverage-reports";
import { getIdGeneratorService } from "@selfsignal/adapters";
import type { AdapterDynamoDBClient } from "@selfsignal/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCoverageReport,
  ExecuteGetCoverageReport,
  ExecuteGetLatestCoverageReport,
  ExecuteListCoverageReports,
} from "@selfsignal/services/coverage-reports/usecases";
// Ports (interfaces)
import type {
  CoverageReportRepository,
  LatestRepository,
} from "@selfsignal/services/coverage-reports/ports";

export interface CoverageReportsDomainModule {
  repos: {
    coverageReports: CoverageReportRepository;
    latests: LatestRepository;
  };
  useCases: {
    coverageReports: {
      create: ExecuteCreateCoverageReport;
      get: ExecuteGetCoverageReport;
      list: ExecuteListCoverageReports;
    };
    latests: {
      get: ExecuteGetLatestCoverageReport;
    };
  };
}

export function buildCoverageReportsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CoverageReportsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      coverageReports?: CoverageReportRepository;
      latests?: LatestRepository;
    } = {};

    obj.coverageReports = new CoverageReportRepositoryAdapter(dynamoClient);
    obj.latests = new LatestRepositoryAdapter(dynamoClient);
    return {
      coverageReports: obj.coverageReports!,
      latests: obj.latests!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    coverageReports: {
      create: new ExecuteCreateCoverageReport(executionContext, idGenerator, repos.coverageReports),
      get: new ExecuteGetCoverageReport(executionContext, idGenerator, repos.coverageReports),
      list: new ExecuteListCoverageReports(executionContext, idGenerator, repos.coverageReports),
    },
    latests: {
      get: new ExecuteGetLatestCoverageReport(executionContext, idGenerator, repos.latests),
    },
  };
  return { repos, useCases: useCases as CoverageReportsDomainModule["useCases"] };
}
