/**
 * ReplaySignalActivation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signal-activations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { replaySignalActivation } from "/api-server/domains/signal-activations/handlers";
import type { SignalActivationsDDDDependencies } from "/api-server/domains/signal-activations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { SIGNALACTIVATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("ReplaySignalActivation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SignalActivationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SignalActivationsDDDDependencies>(
      SIGNALACTIVATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeReplaySignalActivation, "execute").mockResolvedValue(useCaseResult);

    await replaySignalActivation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeReplaySignalActivation.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
