/**
 * GetSignalActivation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: signal-activations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetSignalActivationParams } from "@selfsignal/core/signal-activations";

export function createGetSignalActivationRequest(overrides: Partial<GetSignalActivationParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
