/**
 * GetDataPack DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DownloadVaultDataPackParams } from "@selfsignal/core/vault-profiles";

export function createGetDataPackRequest(overrides: Partial<DownloadVaultDataPackParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
