/**
 * ComplaintCase Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaint-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ComplaintCaseEntity } from "@selfsignal/core/complaint-cases/models/index.js";
import { complaintCasesSchemas } from "@selfsignal/core/complaint-cases";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cpc";

export function createComplaintCase(overrides: Partial<ComplaintCaseEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cpc_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    personId: overrides.personId ?? faker.string.uuid(),
    status: overrides.status ?? "open",
    summary: overrides.summary ?? faker.lorem.word(),
    ...overrides,
  };

  return complaintCasesSchemas.ComplaintCase.parse(raw);
}

export function complaintCaseBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createComplaintCase(overrides));
}
