/**
 * Repository interface for Purpose
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: purposes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PurposeEntity
} from "../models/purpose.entity.js";
import type {
  ListPurposesParams,
  Purpose,
  UpdatePurposeRequestInput
} from "../types/index.js";
/**
 * PurposeRepository Interface
 */
export interface PurposeRepository extends CreateUpdateReadRepository<PurposeEntity, Purpose, UpdatePurposeRequestInput, string, ListPurposesParams> {

}
