/**
 * Handlers for Purpose
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: purposes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PurposesDomainModule } from "../dependencies/purposes-ddd.dependencies.js";
import type { CreatePurposeInput, GetPurposeInput, ListPurposesInput, UpdatePurposeInput } from "@selfsignal/services/purposes";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/purposes
 * Operation: listPurposes
 */
export async function listPurposes(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PurposesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPurposesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.purposes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/purposes
 * Operation: createPurpose
 */
export async function createPurpose(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PurposesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreatePurposeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.purposes.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/purposes/{purposeId}
 * Operation: getPurpose
 */
export async function getPurpose(
  request: FastifyRequest<{ Params: { purposeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PurposesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPurposeInput = {
    purposeId: request.params.purposeId,
  };
  const result = await deps.useCases.purposes.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/purposes/{purposeId}
 * Operation: updatePurpose
 */
export async function updatePurpose(
  request: FastifyRequest<{ Params: { purposeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PurposesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdatePurposeInput = {
    purposeId: request.params.purposeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.purposes.update.execute(input);
  return reply.code(200).send(result);
}


