/**
 * Campaign Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CampaignEntity } from "@selfsignal/core/campaigns/models/index.js";
import { campaignsSchemas } from "@selfsignal/core/campaigns";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cmp";

export function createCampaign(overrides: Partial<CampaignEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cmp_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    fineRiskScore: overrides.fineRiskScore ?? faker.number.int(),
    name: overrides.name ?? faker.person.fullName(),
    purposeId: overrides.purposeId ?? faker.string.uuid(),
    status: overrides.status ?? "draft",
    ...overrides,
  };

  return campaignsSchemas.Campaign.parse(raw);
}

export function campaignBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCampaign(overrides));
}
