/**
 * Purpose Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: purposes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/purposes.openapi.types.js";
import { schemas } from "../schemas/purposes.schemas.js";

/**
 * Entity: PurposeEntity
 * Description: Represents the Purpose domain model.
 * Source: schemas.Purpose
 * Type: Domain Entity (API)
 */
export const PurposeEntitySchema = schemas.Purpose;
export type PurposeEntity = components["schemas"]["Purpose"];
