/**
 * DataPackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataPackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataPackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataPackRepository,
} from "@selfsignal/services/vault-profiles";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataPackRepositoryDdb } from "./data-pack-repository.ddb.js";

/**
 * DataPackRepositoryAdapter
 *
 * Implements DataPackRepository port for infrastructure layer.
 */
export class DataPackRepositoryAdapter implements DataPackRepository {
  private readonly ddb: DataPackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataPackRepositoryDdb(this.dynamoClient);
  }

  async downloadVaultDataPack(input: Parameters<DataPackRepository['downloadVaultDataPack']>[0]): Promise<Awaited<ReturnType<DataPackRepository['downloadVaultDataPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.downloadVaultDataPack(input);
  }
}
