/**
 * VaultProfileRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VaultProfileRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VaultProfileRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VaultProfileRepository,
} from "@selfsignal/services/vault-profiles";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VaultProfileRepositoryDdb } from "./vault-profile-repository.ddb.js";

/**
 * VaultProfileRepositoryAdapter
 *
 * Implements VaultProfileRepository port for infrastructure layer.
 */
export class VaultProfileRepositoryAdapter implements VaultProfileRepository {
  private readonly ddb: VaultProfileRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VaultProfileRepositoryDdb(this.dynamoClient);
  }

  async listVaultProfiles(input: Parameters<VaultProfileRepository['listVaultProfiles']>[0]): Promise<Awaited<ReturnType<VaultProfileRepository['listVaultProfiles']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listVaultProfiles(input);
  }

  async createVaultProfile(input: Parameters<VaultProfileRepository['createVaultProfile']>[0]): Promise<Awaited<ReturnType<VaultProfileRepository['createVaultProfile']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createVaultProfile(input);
  }

  async getVaultProfile(input: Parameters<VaultProfileRepository['getVaultProfile']>[0]): Promise<Awaited<ReturnType<VaultProfileRepository['getVaultProfile']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getVaultProfile(input);
  }

  async updateVaultProfile(input: Parameters<VaultProfileRepository['updateVaultProfile']>[0]): Promise<Awaited<ReturnType<VaultProfileRepository['updateVaultProfile']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateVaultProfile(input);
  }
}
