/**
 * ExecuteRenewConsentGrant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent-grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRenewConsentGrant Use Case
 *
 * DDD: Application use case for get Renew.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RenewConsentGrantInput, RenewConsentGrantOutput } from "../dto/renew.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { RenewRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRenewConsentGrant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly renew: RenewRepository
  ) {}

  async execute(input: RenewConsentGrantInput): Promise<RenewConsentGrantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cgrId();

    // All field names extracted from OpenAPI spec: expiresAt
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).grantId) {
      throw new ValidationError("grantId is required");
    }
    const grantId = (input as any).grantId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.renew.renewConsentGrant({ grantId: grantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${grantId}`);
    }

    return entity as RenewConsentGrantOutput;
  }
}
