/**
 * GetComplaintCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaint-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getComplaintCase } from "/api-server/domains/complaint-cases/handlers";
import type { ComplaintCasesDDDDependencies } from "/api-server/domains/complaint-cases";
import { createComplaintCase as createComplaintCaseEntity } from "/factories/complaint-cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { COMPLAINTCASES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetComplaintCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ComplaintCasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ComplaintCasesDDDDependencies>(
      COMPLAINTCASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createComplaintCaseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetComplaintCase, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { complaintId: entity.id };

    await getComplaintCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetComplaintCase.execute).toHaveBeenCalledWith(expect.objectContaining({ complaintId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { complaintId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetComplaintCase, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getComplaintCase(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
