/**
 * Repository interface for Campaign
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CampaignEntity
} from "../models/campaign.entity.js";
import type {
  ListCampaignsParams,
  Campaign
} from "../types/index.js";
/**
 * CampaignRepository Interface
 */
export interface CampaignRepository extends CreateReadRepository<CampaignEntity, Campaign, string, ListCampaignsParams> {

}
