/**
 * ExecuteDownloadVaultDataPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDownloadVaultDataPack Use Case
 *
 * DDD: Application use case for get DataPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DownloadVaultDataPackInput, DownloadVaultDataPackOutput } from "../dto/data-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { DataPackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDownloadVaultDataPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataPack: DataPackRepository
  ) {}

  async execute(input: DownloadVaultDataPackInput): Promise<DownloadVaultDataPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vpfId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).personId) {
      throw new ValidationError("personId is required");
    }
    const personId = (input as any).personId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dataPack.downloadVaultDataPack({ personId: personId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${personId}`);
    }

    return entity as DownloadVaultDataPackOutput;
  }
}
