/**
 * ExecuteGetVaultProfile - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetVaultProfile Use Case
 *
 * DDD: Application use case for get VaultProfile.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetVaultProfileInput, GetVaultProfileOutput } from "../dto/vault-profile.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { VaultProfileRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetVaultProfile {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vaultProfile: VaultProfileRepository
  ) {}

  async execute(input: GetVaultProfileInput): Promise<GetVaultProfileOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vpfId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).personId) {
      throw new ValidationError("personId is required");
    }
    const personId = (input as any).personId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.vaultProfile.getVaultProfile({ personId: personId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${personId}`);
    }

    return entity as GetVaultProfileOutput;
  }
}
