/**
 * ComplianceGate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplianceGate DTOs
 *
 * DDD: Application DTOs for ComplianceGate use cases.
 */

import type { RunCampaignComplianceGateParams } from "@selfsignal/core/campaigns/types";

export type RunCampaignComplianceGateInput = RunCampaignComplianceGateParams;

export type RunCampaignComplianceGateOutput = {};
