/**
 * CampaignRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CampaignRepository Port
 *
 * DDD: Application port for campaignrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCampaignInput, CreateCampaignOutput, GetCampaignInput, GetCampaignOutput, ListCampaignsInput, ListCampaignsOutput } from "../dto/campaign.dto";
export interface CampaignRepository {
  listCampaigns(input: ListCampaignsInput): Promise<ListCampaignsOutput>;
  createCampaign(input: CreateCampaignInput): Promise<CreateCampaignOutput>;
  getCampaign(input: GetCampaignInput): Promise<GetCampaignOutput>;
}

export type { CreateCampaignInput, CreateCampaignOutput, GetCampaignInput, GetCampaignOutput, ListCampaignsInput, ListCampaignsOutput } from "../dto/campaign.dto";
