/**
 * CreateCoverageReport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: coverage-reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createCoverageReport } from "/api-server/domains/coverage-reports/handlers";
import type { CoverageReportsDDDDependencies } from "/api-server/domains/coverage-reports";
import { createCoverageReport as createCoverageReportEntity } from "/factories/coverage-reports";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { COVERAGEREPORTS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateCoverageReport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CoverageReportsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CoverageReportsDDDDependencies>(
      COVERAGEREPORTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createCoverageReportEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateCoverageReport, "execute").mockResolvedValue(useCaseResult);

    await createCoverageReport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateCoverageReport.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
