/**
 * GetCoverageReport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: coverage-reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getCoverageReport } from "/api-server/domains/coverage-reports/handlers";
import type { CoverageReportsDDDDependencies } from "/api-server/domains/coverage-reports";
import { createCoverageReport as createCoverageReportEntity } from "/factories/coverage-reports";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { COVERAGEREPORTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetCoverageReport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CoverageReportsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CoverageReportsDDDDependencies>(
      COVERAGEREPORTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createCoverageReportEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetCoverageReport, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { reportId: entity.id };

    await getCoverageReport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetCoverageReport.execute).toHaveBeenCalledWith(expect.objectContaining({ reportId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { reportId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetCoverageReport, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getCoverageReport(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
