/**
 * AuditExport Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AuditExportEntity } from "@selfsignal/core/audit-exports/models/index.js";
import { auditExportsSchemas } from "@selfsignal/core/audit-exports";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "aud";

export function createAuditExport(overrides: Partial<AuditExportEntity> = {}) {
  const raw = {
    id: overrides.id ?? `aud_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    periodEnd: overrides.periodEnd ?? new Date().toISOString(),
    periodStart: overrides.periodStart ?? new Date().toISOString(),
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return auditExportsSchemas.AuditExport.parse(raw);
}

export function auditExportBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAuditExport(overrides));
}
