/**
 * ComplaintCase DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaint-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplaintCase DTOs
 *
 * DDD: Application DTOs for ComplaintCase use cases.
 */

import type { GetComplaintCaseParams, ListComplaintCasesParams, OpenComplaintCaseRequestInput } from "@selfsignal/core/complaint-cases/types";

export type ListComplaintCasesInput = ListComplaintCasesParams;

export type OpenComplaintCaseInput = OpenComplaintCaseRequestInput;

export type GetComplaintCaseInput = GetComplaintCaseParams;

export type ListComplaintCasesOutput = {};

export type OpenComplaintCaseOutput = {};

export type GetComplaintCaseOutput = {};
