/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audit-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@selfsignal/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@selfsignal/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@selfsignal/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _auditExports from "./audit-exports/index.js";
import * as _campaigns from "./campaigns/index.js";
import * as _complaintCases from "./complaint-cases/index.js";
import * as _consentGrants from "./consent-grants/index.js";
import * as _coverageReports from "./coverage-reports/index.js";
import * as _identity from "./identity/index.js";
import * as _integrations from "./integrations/index.js";
import * as _purposes from "./purposes/index.js";
import * as _rightsRequests from "./rights-requests/index.js";
import * as _signalActivations from "./signal-activations/index.js";
import * as _vaultProfiles from "./vault-profiles/index.js";

// Export as namespaces
export const auditExports = _auditExports;
export const campaigns = _campaigns;
export const complaintCases = _complaintCases;
export const consentGrants = _consentGrants;
export const coverageReports = _coverageReports;
export const identity = _identity;
export const integrations = _integrations;
export const purposes = _purposes;
export const rightsRequests = _rightsRequests;
export const signalActivations = _signalActivations;
export const vaultProfiles = _vaultProfiles;
