/**
 * ConsentGrant Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent-grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/consent-grants.openapi.types.js";
import { schemas } from "../schemas/consent-grants.schemas.js";

/**
 * Entity: ConsentGrantEntity
 * Description: Represents the ConsentGrant domain model.
 * Source: schemas.ConsentGrant
 * Type: Domain Entity (API)
 */
export const ConsentGrantEntitySchema = schemas.ConsentGrant;
export type ConsentGrantEntity = components["schemas"]["ConsentGrant"];
