/**
 * Repository interface for VaultProfile
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  VaultProfileEntity
} from "../models/vault-profile.entity.js";
import type {
  ListVaultProfilesParams,
  VaultProfile,
  UpdateVaultProfileRequestInput
} from "../types/index.js";
/**
 * VaultProfileRepository Interface
 */
export interface VaultProfileRepository extends CreateUpdateReadRepository<VaultProfileEntity, VaultProfile, UpdateVaultProfileRequestInput, string, ListVaultProfilesParams> {

}
