/**
 * Erase DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vault-profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Erase DTOs
 *
 * DDD: Application DTOs for Erase use cases.
 */

import type { EraseVaultProfileParams } from "@selfsignal/core/vault-profiles/types";

export type EraseVaultProfileInput = EraseVaultProfileParams;

export type EraseVaultProfileOutput = {};
