/**
 * GetPublicAttestation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPublicAttestation } from "/api-server/domains/audit-exports/handlers";
import type { AuditExportsDDDDependencies } from "/api-server/domains/audit-exports";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { AUDITEXPORTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPublicAttestation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditExportsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditExportsDDDDependencies>(
      AUDITEXPORTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPublicAttestation, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { exportId: entity.id };

    await getPublicAttestation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPublicAttestation.execute).toHaveBeenCalledWith(expect.objectContaining({ exportId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { exportId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPublicAttestation, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPublicAttestation(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
