/**
 * ListConsentGrants handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consent-grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listConsentGrants } from "/api-server/domains/consent-grants/handlers";
import type { ConsentGrantsDDDDependencies } from "/api-server/domains/consent-grants";
import { createConsentGrant as createConsentGrantEntity } from "/factories/consent-grants";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { CONSENTGRANTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListConsentGrants", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsentGrantsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsentGrantsDDDDependencies>(
      CONSENTGRANTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createConsentGrantEntity({ orgId }),
      createConsentGrantEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListConsentGrants, "execute").mockResolvedValue(useCaseResult);

    await listConsentGrants(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListConsentGrants.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
