/**
 * RightsRequest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights-requests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RightsRequest DTOs
 *
 * DDD: Application DTOs for RightsRequest use cases.
 */

import type { CreateRightsRequestRequestInput, GetRightsRequestParams, ListRightsRequestsParams } from "@selfsignal/core/rights-requests/types";

export type ListRightsRequestsInput = ListRightsRequestsParams;

export type CreateRightsRequestInput = CreateRightsRequestRequestInput;

export type GetRightsRequestInput = GetRightsRequestParams;

export type ListRightsRequestsOutput = {};

export type CreateRightsRequestOutput = {};

export type GetRightsRequestOutput = {};
