/**
 * CampaignRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CampaignRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CampaignRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CampaignRepository,
} from "@selfsignal/services/campaigns";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CampaignRepositoryDdb } from "./campaign-repository.ddb.js";

/**
 * CampaignRepositoryAdapter
 *
 * Implements CampaignRepository port for infrastructure layer.
 */
export class CampaignRepositoryAdapter implements CampaignRepository {
  private readonly ddb: CampaignRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CampaignRepositoryDdb(this.dynamoClient);
  }

  async listCampaigns(input: Parameters<CampaignRepository['listCampaigns']>[0]): Promise<Awaited<ReturnType<CampaignRepository['listCampaigns']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCampaigns(input);
  }

  async createCampaign(input: Parameters<CampaignRepository['createCampaign']>[0]): Promise<Awaited<ReturnType<CampaignRepository['createCampaign']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createCampaign(input);
  }

  async getCampaign(input: Parameters<CampaignRepository['getCampaign']>[0]): Promise<Awaited<ReturnType<CampaignRepository['getCampaign']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCampaign(input);
  }
}
