/**
 * ComplaintCaseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaint-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplaintCaseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ComplaintCaseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ComplaintCaseRepository,
} from "@selfsignal/services/complaint-cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ComplaintCaseRepositoryDdb } from "./complaint-case-repository.ddb.js";

/**
 * ComplaintCaseRepositoryAdapter
 *
 * Implements ComplaintCaseRepository port for infrastructure layer.
 */
export class ComplaintCaseRepositoryAdapter implements ComplaintCaseRepository {
  private readonly ddb: ComplaintCaseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ComplaintCaseRepositoryDdb(this.dynamoClient);
  }

  async listComplaintCases(input: Parameters<ComplaintCaseRepository['listComplaintCases']>[0]): Promise<Awaited<ReturnType<ComplaintCaseRepository['listComplaintCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listComplaintCases(input);
  }

  async openComplaintCase(input: Parameters<ComplaintCaseRepository['openComplaintCase']>[0]): Promise<Awaited<ReturnType<ComplaintCaseRepository['openComplaintCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openComplaintCase(input);
  }

  async getComplaintCase(input: Parameters<ComplaintCaseRepository['getComplaintCase']>[0]): Promise<Awaited<ReturnType<ComplaintCaseRepository['getComplaintCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getComplaintCase(input);
  }
}
