/**
 * Routes for Escalate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: complaint-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { escalateComplaintCase } from "../handlers/escalate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function escalateRoutes(fastify: FastifyInstance) {
  // POST /v1/complaint-cases/{complaintId}/escalate (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/complaint-cases/:complaintId/escalate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { complaintId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getComplaintCasesDependenciesForRequest();
        await escalateComplaintCase(request, reply, deps);
      });
    }
  );


}
