/**
 * ExecuteListPurposes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: purposes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPurposes Use Case
 *
 * DDD: Application use case for list Purpose.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPurposesInput, ListPurposesOutput } from "../dto/purpose.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { PurposeRepository } from "../ports";

export class ExecuteListPurposes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly purpose: PurposeRepository
  ) {}

  async execute(input: ListPurposesInput): Promise<ListPurposesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.purId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.purpose.listPurposes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPurposesOutput;
  }
}
