/**
 * ExecuteGetPurpose - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: purposes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPurpose Use Case
 *
 * DDD: Application use case for get Purpose.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPurposeInput, GetPurposeOutput } from "../dto/purpose.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { PurposeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPurpose {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly purpose: PurposeRepository
  ) {}

  async execute(input: GetPurposeInput): Promise<GetPurposeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.purId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).purposeId) {
      throw new ValidationError("purposeId is required");
    }
    const purposeId = (input as any).purposeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.purpose.getPurpose({ purposeId: purposeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${purposeId}`);
    }

    return entity as GetPurposeOutput;
  }
}
