/**
 * CreateVerify DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { VerifyAuditExportParams } from "@selfsignal/core/audit-exports";

export function createCreateVerifyRequest(overrides: Partial<VerifyAuditExportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
