/**
 * GetCampaign handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getCampaign } from "/api-server/domains/campaigns/handlers";
import type { CampaignsDDDDependencies } from "/api-server/domains/campaigns";
import { createCampaign as createCampaignEntity } from "/factories/campaigns";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "/tests/shared";
import { CAMPAIGNS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetCampaign", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CampaignsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CampaignsDDDDependencies>(
      CAMPAIGNS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createCampaignEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetCampaign, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { campaignId: entity.id };

    await getCampaign(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetCampaign.execute).toHaveBeenCalledWith(expect.objectContaining({ campaignId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { campaignId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetCampaign, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getCampaign(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
