/**
 * ExecuteGetIntegration - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: integrations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetIntegration Use Case
 *
 * DDD: Application use case for get Integration.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetIntegrationInput, GetIntegrationOutput } from "../dto/integration.dto";
import type { ExecutionContextService, IdGeneratorService } from "@selfsignal/services/_shared/index.js";
import type { IntegrationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetIntegration {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly integration: IntegrationRepository
  ) {}

  async execute(input: GetIntegrationInput): Promise<GetIntegrationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.intId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).integrationId) {
      throw new ValidationError("integrationId is required");
    }
    const integrationId = (input as any).integrationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.integration.getIntegration({ integrationId: integrationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${integrationId}`);
    }

    return entity as GetIntegrationOutput;
  }
}
